//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/InputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControls"",
    ""maps"": [
        {
            ""name"": ""AndroidMap"",
            ""id"": ""6917caff-694e-4881-bbe1-89029e3f49a5"",
            ""actions"": [
                {
                    ""name"": ""Tap"",
                    ""type"": ""Button"",
                    ""id"": ""fcbcd19e-73ef-4fa1-8db3-c6da1dc9715d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""490ad96a-f958-4373-83e2-32da92da2dd5"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // AndroidMap
        m_AndroidMap = asset.FindActionMap("AndroidMap", throwIfNotFound: true);
        m_AndroidMap_Tap = m_AndroidMap.FindAction("Tap", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // AndroidMap
    private readonly InputActionMap m_AndroidMap;
    private List<IAndroidMapActions> m_AndroidMapActionsCallbackInterfaces = new List<IAndroidMapActions>();
    private readonly InputAction m_AndroidMap_Tap;
    public struct AndroidMapActions
    {
        private @InputControls m_Wrapper;
        public AndroidMapActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Tap => m_Wrapper.m_AndroidMap_Tap;
        public InputActionMap Get() { return m_Wrapper.m_AndroidMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AndroidMapActions set) { return set.Get(); }
        public void AddCallbacks(IAndroidMapActions instance)
        {
            if (instance == null || m_Wrapper.m_AndroidMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AndroidMapActionsCallbackInterfaces.Add(instance);
            @Tap.started += instance.OnTap;
            @Tap.performed += instance.OnTap;
            @Tap.canceled += instance.OnTap;
        }

        private void UnregisterCallbacks(IAndroidMapActions instance)
        {
            @Tap.started -= instance.OnTap;
            @Tap.performed -= instance.OnTap;
            @Tap.canceled -= instance.OnTap;
        }

        public void RemoveCallbacks(IAndroidMapActions instance)
        {
            if (m_Wrapper.m_AndroidMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAndroidMapActions instance)
        {
            foreach (var item in m_Wrapper.m_AndroidMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AndroidMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public AndroidMapActions @AndroidMap => new AndroidMapActions(this);
    public interface IAndroidMapActions
    {
        void OnTap(InputAction.CallbackContext context);
    }
}
